# Configuration file for gptgodmc
# Make sure you update this before running!

# your OpenAi API key from https://platform.openai.com/api-keys
# the plugin won't work without this

openAiKey: ""

# language in ISO-639 format https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
language: en

# if set to true:
# - When players die they are put in spectator mode
# - When everyone dies the map is reset
# This is the intended way to play
# only set to false for testing and debugging
Rounds: true

# the world the server will load on starting
# worlds are stored in plugins/gptgodmc/worlds
# if empty or invalid the Round System won't work
startingWorld: ""